version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: inst-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASS}
      MINIO_REGION: ${MINIO_REGION}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data: