version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: inst-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    volumes:
      minio_data:/data

  minio-client:
    image: minio/mc:latest
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host rm expo;
      /usr/bin/mc config host add --quiet --api s3v4 local http://minio:9000 minio minio123;
      /usr/bin/mc rb --force local/<your-bucket-name>/;
      /usr/bin/mc mb --quiet local/<your-bucket-name>/;
      /usr/bin/mc policy set public local/<your-bucket-name>;
      "
    depends_on:
      - minio