services:
  web:
    image: imagine:1.0.0
    container_name: serv-django
    command: ["sh", "-c", "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    environment:
      - .env
      - VIRTUAL_HOST=${DOMAIN_NAME}
    ports:
      - "8000:8000"
    networks:
      default:
        aliases:
          - ${DOMAIN_NAME}
